server:
  port: 4001 # Gateway listens on port 4001

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:4002
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        # Route for /api/collaborateurs/** to patient-service
        - id: collaborateurs-service-route
          uri: http://localhost:4003
          predicates:
            - Path=/api/collaborateurs/**
          filters:
            - StripPrefix=1
            - AdminJwtValidation

        # Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://localhost:4003
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs