server:
  port: 4001 # Gateway listens on port 4001

spring:
  cloud:
    gateway:
      routes:

 #---------------------------------------------------------------------------------------------------------------------# swagger-ui/index.html

        # For authentication
        - id: auth-service-route
          uri: http://localhost:4002
          predicates:
            - Path=/auth/**

        # For doc authentication
        - id: doc-auth-service-route
          uri: http://localhost:4002
          predicates:
            - Path=/api-doc/auth/
          filters:
            - SetPath=/v3/api-docs
#---------------------------------------------------------------------------------------------------------------------#

        # Route for /api/collaborateurs/** to collaborateur
        - id: collaborateurs-service-route
          uri: http://localhost:4003
          predicates:
            - Path=/api/collaborateurs/**
          filters:
            - StripPrefix=1
            - AdminJwtValidation

        # Route for /api/docs/collaborateurs to collaborateurs-service /v3/api-docs
        - id: api-docs-collaborateurs-route
          uri: http://localhost:4003
          predicates:
            - Path=/api-docs/collaborateurs
          filters:
            - SetPath=/v3/api-docs

#---------------------------------------------------------------------------------------------------------------------#

        # Routes for Admin Formations Management
        - id: api-admin-formation-management
          uri: http://localhost:4004
          predicates:
            - Path=/api/admin/formations/**
          filters:
            - AdminJwtValidation


        # Routes for Admin Formations Management
        - id: api-collaborateur-formation-management
          uri: http://localhost:4004
          predicates:
            - Path=/api/collaborateur/formations/**
          filters:
            - CollaborateurJwtValidation

        # Route for /api/docs/collaborateurs to collaborateurs-service /v3/api-docs
        - id: api-docs-formation-management-route
          uri: http://localhost:4004
          predicates:
            - Path=/api-docs/formations
          filters:
            - RewritePath=/api-docs/formations,/v3/api-docs

#---------------------------------------------------------------------------------------------------------------------#


        # Route for /api//notifications to notification for administrators
        - id: api-admin-notifications
          uri: http://localhost:4005
          predicates:
            - Path=/api/notifications/admin/**
          filters:
            - AdminJwtValidation

        # Route for /api//notifications to notification for users / collaborateurs
        - id: api-admin-notifications
          uri: http://localhost:4005
          predicates:
            - Path=/api/notifications/user/**
          filters:
            - CollaborateurJwtValidation

#---------------------------------------------------------------------------------------------------------------------#

        # Route for /api//notifications to chatbot
        - id: api-admin-notifications
          uri: http://localhost:4006
          predicates:
            - Path=/api/chat
          filters:
            - CollaborateurJwtValidation

